BOARD = lstep
LATENCY = -1
ERRORS = 
LOGIC_TA = 128
DESIGN_ARCH = main
PHYS_REGS = 574
PHYS_LUTS = 798
LOGIC_TIME__ACTUAL_PERIOD = 9.573000
LOGIC_TIME__ACTUAL_SPEED = 104
LOGIC_TIME__TIMING_PATHS = ( 9.573000, 9.304000, 0.269000, u_lab3_column/q(0), u_lab3_reg_p(31)/d,  ), ( 9.404000, 9.135000, 0.269000, u_lab3_column/q(1), u_lab3_reg_p(31)/d,  ), ( 9.048000, 8.779000, 0.269000, u_lab3_re...end(0)(0), u_lab3_reg_p(31)/d,  ), ( 9.005000, 8.736000, 0.269000, u_lab3_re...end(0)(0), u_lab3_reg_p(31)/d,  ), ( 8.969000, 8.700000, 0.269000, u_lab3_re...end(0)(1), u_lab3_reg_p(31)/d,  )

PHYS_AREA = 943
LOGIC_REGS = 574
PHYS_TA = 104.528102
OPT_EFFORT = 0
RPT_DIR = RPT
LOGIC_AREA = 808
DESIGN_ENTITY = lab3_top
LOGIC_TA_LAT = 128
PHYS_TIME__ACTUAL_PERIOD = 10.145075
PHYS_TIME__ACTUAL_SPEED = 98.570000

LOGIC_LUTS = 808
