OPT_EFFORT_PHYS = 0
PY_DESIGN_VHDL = [ "myflipflop.vhd" ]
INTERACTIVE_FLAG = True
PART = 
BOARD = MODGEN
OPT_EFFORT_LOGIC_1 = 0
OPT_EFFORT_LOGIC_2 = 0
DESIGN_ENTITY = myflipflop
FAMILY_SHORT = modgen_sim
SH_DESIGN_VHDL = myflipflop.vhd
DESIGN_ARCH = 
SH_FAB_SIM_LIBS = /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives /opt-src/CMC/local/maagaard/kits-sim/modgen_sim
RUN_SHIM = True
ASIC = False
OLD_DC_SHELL = False
SIM_TOOL = MODELSIM

OPT_EFFORT = 0
GENERICS = {  }
ECE327 = /home/ece327
LIB_VHDL = 
SH_LIB_VHDL = 
GOAL_FREQ = 
USE_GUI = True
PHYS_SYNTH_TOOL = 
RPT_DIR = RPT
FAB_SIM_LIBS = /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives, /opt-src/CMC/local/maagaard/kits-sim/modgen_sim
PY_FAB_SIM_LIBS = [ "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives", "/opt-src/CMC/local/maagaard/kits-sim/modgen_sim" ]
LOGIC_SYNTH_EXT = vhd
RPT_TDIR = RPT
FAMILY_LONG = modgen_sim
TCL_DESIGN_VHDL = { myflipflop.vhd }
USER_TOOL_FLAGS = 
DESIGN_VHDL = myflipflop.vhd
GUI_FLAG = -newgui
UWP = myflipflop
TCL_FAB_SIM_LIBS = { /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives /opt-src/CMC/local/maagaard/kits-sim/modgen_sim }
LC_FAMILY_SHORT = modgen_sim
PROG = uw-synth
TCL_LIB_VHDL = {  }
SPEED = 
LOGIC_SYNTH_TOOL = PRECISION_RTL
PY_LIB_VHDL = []
