PY_TB_VHDL = [ "util_unsynth.vhd", "mult_tb.vhd" ]
OPT_EFFORT_PHYS = 0
PY_DESIGN_VHDL = [ "mult.vhd" ]

USER_TOOL_FLAGS = 
PART = 
DESIGN_ARCH = main
RUN_SHIM = True
SIM_TOOL = MODELSIM
SH_FAB_SIM_LIBS = /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives /opt-src/CMC/local/maagaard/kits-sim/modgen_sim
ECE327 = /home/ece327
SH_TB_VHDL = util_unsynth.vhd mult_tb.vhd
TB_ENTITY = mult_tb
GOAL_FREQ = 
RPT_DIR = RPT
PY_FAB_SIM_LIBS = [ "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm", "/opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives", "/opt-src/CMC/local/maagaard/kits-sim/modgen_sim" ]
LOGIC_SYNTH_TOOL = PRECISION_RTL
TCL_FAB_SIM_LIBS = { /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives /opt-src/CMC/local/maagaard/kits-sim/modgen_sim }
TCL_TB_VHDL = { util_unsynth.vhd mult_tb.vhd }
GUI_FLAG = -newgui
BOARD = MODGEN
INTERACTIVE_FLAG = True
TB_ARCH = main
OPT_EFFORT_LOGIC_1 = 0
OPT_EFFORT_LOGIC_2 = 0
DESIGN_ENTITY = mult
FAMILY_SHORT = modgen_sim
SH_DESIGN_VHDL = mult.vhd
ASIC = False
LC_FAMILY_SHORT = modgen_sim
OPT_EFFORT = 0
GENERICS = {  }
LIB_VHDL = util.vhd
SH_LIB_VHDL = util.vhd
USE_GUI = True
TB_VHDL = util_unsynth.vhd, mult_tb.vhd
SIM_SCRIPT = mult_tb.sim
FAB_SIM_LIBS = /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_mf, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/lpm, /opt-src/CMC/local/maagaard/kits-sim/altera-15.1/altera_primitives, /opt-src/CMC/local/maagaard/kits-sim/modgen_sim
LOGIC_SYNTH_EXT = vhd
RPT_TDIR = RPT
FAMILY_LONG = modgen_sim
TCL_DESIGN_VHDL = { mult.vhd }
SPEED = 
UWP = mult
OLD_DC_SHELL = False
PHYS_SYNTH_TOOL = 
PROG = uw-synth
TCL_LIB_VHDL = { util.vhd }
DESIGN_VHDL = mult.vhd
PY_LIB_VHDL = [ "util.vhd" ]
